### ISSUE TITLE
PrivatePayload Definition

### ISSUE THREAD

**Issue by ricejasonf** [ricejasonf/nbdl#9]
There is existing code to allow an additional payload attached to upstream create messages. Currently, this information is not a part of the access point meta object so it can never be set. It would probably be best to put the definition for it in the `AccessPoint` itself and never store any information in `Actions`.

Something like this:

``` yaml
AccessPoint:
  EntityName: "foo"
  Actions: [ Create, Read, Update, Delete ]
  PrivatePayload: my_ns::my_private_payload
```
